# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: social_map_dev
  pool: 5
  timeout: 5000
  username: social_map

test:
  adapter: postgresql
  database: social_map_test
  pool: 5
  timeout: 5000
  username: social_map